//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeadShop.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lead()
        {
            this.Calls = new HashSet<Call>();
        }
    
        public int LeadId { get; set; }
        public int StatusLeadId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public decimal WorkWithObjections { get; set; }
        public decimal SellingSkill { get; set; }
        public decimal ProductKnowledge { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual StatusLead StatusLead { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Call> Calls { get; set; }
    }
}
